### ISSUE TITLE
Make <em> the same size as rest of text

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/editorial-styleguide#4]
![screen shot 2016-05-17 at 3 54 48 pm](https://cloud.githubusercontent.com/assets/6132788/15337083/ce9d7ef6-1c47-11e6-9b23-fcda1599324a.png)

^ that should all be normal text size

**Comment by streeetlamp** [comment]
![giphy-3](https://cloud.githubusercontent.com/assets/1740634/15339181/30313c76-1c51-11e6-954c-abfe4c440f56.gif)
